# Generated by Django 2.2.6 on 2022-09-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qualityapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operator',
            old_name='operator',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='ec_user',
        ),
    ]
