# Generated by Django 2.2.6 on 2022-09-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityapp', '0003_auto_20220922_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='company',
        ),
        migrations.AddField(
            model_name='operator',
            name='company_ids',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='ec_user',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
