# Generated by Django 2.2.6 on 2022-09-26 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualityapp', '0004_auto_20220926_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('layer', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_format', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_term', models.CharField(blank=True, max_length=100, null=True)),
                ('pcb_name', models.CharField(blank=True, max_length=250, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('preparation_due_date', models.DateTimeField(blank=True, null=True)),
                ('customer_type', models.CharField(blank=True, max_length=500, null=True)),
                ('is_modify', models.BooleanField(default=False)),
                ('is_repeat', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='qualityapp.Company')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='qualityapp.Operator')),
            ],
        ),
        migrations.CreateModel(
            name='OrderScreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_value', models.CharField(max_length=400, null=True)),
                ('display_ids', models.CharField(blank=True, max_length=400, null=True)),
                ('is_compulsory', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderscreen_company', to='qualityapp.Company')),
                ('order_screen_parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qualityapp.OrderScreenParameter')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTechParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_include_assembly', models.BooleanField(default=False)),
                ('is_top_stencil', models.BooleanField(default=False)),
                ('is_bottom_stencil', models.BooleanField(default=False)),
                ('pcb_separation_method', models.CharField(blank=True, max_length=100, null=True)),
                ('board_thickness', models.CharField(blank=True, max_length=100, null=True)),
                ('material_tg', models.CharField(blank=True, max_length=100, null=True)),
                ('buildup_code', models.CharField(blank=True, max_length=100, null=True)),
                ('outer_layer_copper_foil', models.IntegerField(blank=True, null=True)),
                ('inner_layer_copper_foil', models.IntegerField(blank=True, null=True)),
                ('is_special_buildup', models.BooleanField(default=False)),
                ('inner_layer_core_thickness', models.IntegerField(blank=True, null=True)),
                ('blind_buried_via_runs', models.CharField(blank=True, max_length=100, null=True)),
                ('is_defined_impedance', models.BooleanField(default=False)),
                ('top_solder_mask', models.CharField(blank=True, max_length=100, null=True)),
                ('bottom_solder_mask', models.CharField(blank=True, max_length=100, null=True)),
                ('top_legend', models.CharField(blank=True, max_length=100, null=True)),
                ('bottom_legend', models.CharField(blank=True, max_length=100, null=True)),
                ('surface_finish', models.CharField(blank=True, max_length=100, null=True)),
                ('is_bare_board_testing', models.BooleanField(default=False)),
                ('peelable_mask', models.CharField(blank=True, max_length=100, null=True)),
                ('carbon_contacts', models.CharField(blank=True, max_length=100, null=True)),
                ('ul_marking', models.BooleanField(default=False)),
                ('specific_marking', models.BooleanField(default=False)),
                ('pth_on_the_board_edge', models.BooleanField(default=False)),
                ('round_edge_plating', models.BooleanField(default=False)),
                ('copper_upto_board_edge', models.BooleanField(default=False)),
                ('press_fit_holes', models.BooleanField(default=False)),
                ('chamfered_holes', models.BooleanField(default=False)),
                ('depth_routing', models.BooleanField(default=False)),
                ('edge_connector_gold_surface', models.IntegerField(blank=True, null=True)),
                ('edge_connector_bevelling', models.CharField(blank=True, max_length=100, null=True)),
                ('top_heat_sink_paste', models.CharField(blank=True, max_length=100, null=True)),
                ('bottom_heat_sink_paste', models.CharField(blank=True, max_length=100, null=True)),
                ('tool_nr', models.CharField(blank=True, max_length=100, null=True)),
                ('prod_panelSize', models.CharField(blank=True, max_length=100, null=True)),
                ('via_filling_hole_plugging', models.CharField(blank=True, max_length=100, null=True)),
                ('is_nda', models.BooleanField(default=False)),
                ('is_qta', models.BooleanField(default=False)),
                ('due_time', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('tool_spec', models.CharField(blank=True, max_length=100, null=True)),
                ('logistics_spec', models.CharField(blank=True, max_length=100, null=True)),
                ('removal_nfp_allowed', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_coupon', models.CharField(blank=True, max_length=100, null=True)),
                ('hole_plugging', models.CharField(blank=True, max_length=100, null=True)),
                ('u_via_filling', models.CharField(blank=True, max_length=100, null=True)),
                ('fai', models.CharField(blank=True, max_length=100, null=True)),
                ('cam_remark', models.CharField(blank=True, max_length=100, null=True)),
                ('venting_pattern', models.CharField(blank=True, max_length=100, null=True)),
                ('engineer_1', models.CharField(blank=True, max_length=100, null=True)),
                ('engineer_2', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_query_name='ordertechparameter_order', to='qualityapp.Order')),
            ],
        ),
        migrations.RenameModel(
            old_name='OrderProcessMaster',
            new_name='OrderProcess',
        ),
        migrations.AddField(
            model_name='orderallocationflow',
            name='allocation_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='qualityapp.CompanyUser'),
        ),
        migrations.RenameModel(
            old_name='ServiceMaster',
            new_name='Service',
        ),
        migrations.DeleteModel(
            name='OrderScreenMaster',
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='qualityapp.Service'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='qualityapp.CompanyUser'),
        ),
    ]
