# Generated by Django 2.2.6 on 2022-09-27 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualityapp', '0005_auto_20220926_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertechparameter',
            name='prod_panelSize',
        ),
        migrations.AddField(
            model_name='order',
            name='order_next_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_previous_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderallocationflow',
            name='allocation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderprocess',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordertechparameter',
            name='prod_panel_size',
            field=models.CharField(blank=True, choices=[('prod_panelSize0', '0 x 0'), ('prod_panelSize1', '406 x 355'), ('prod_panelSize2', '440 x 300'), ('prod_panelSize3', '457 x 305'), ('prod_panelSize4', '610 x 457'), ('prod_panelSize5', '610 x 508'), ('prod_panelSize6', '712 x 560'), ('prod_panelSize7', '762 x 610'), ('prod_panelSize8', '305 x 457'), ('prod_panelSize9', '457 x 610'), ('prod_panelSize10', '604 x 524'), ('prod_panelSize11', '624 x 524'), ('prod_panelSize12', '604 x 454'), ('prod_panelSize13', '730 x 530')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_format',
            field=models.CharField(blank=True, choices=[('Single_PCB', 'Single PCB'), ('Panel', 'Panel')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_term',
            field=models.CharField(blank=True, choices=[('DEL_0', '0 Working days'), ('DEL_1', '1 Working days'), ('DEL_2', '2 Working days'), ('DEL_3', '3 Working days'), ('DEL_4', '4 Working days'), ('DEL_5', '5 Working days'), ('DEL_6', '6 Working days'), ('DEL_7', '7 Working days'), ('DEL_8', '8 Working days'), ('DEL_9', '9 Working days'), ('DEL_10', '10 Working days'), ('DEL_12', '12 Working days'), ('DEL_15', '15 Working days'), ('DEL_20', '20 Working days'), ('DEL_25', '25 Working days'), ('DEL_30', '30 Working days'), ('No', 'Not Available')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='layer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='bottom_heat_sink_paste',
            field=models.CharField(blank=True, choices=[('Bot_HSP_No', 'No'), ('Bot_HSP_100', '100 µm'), ('Bot_HSP_200', '200 µm')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='bottom_legend',
            field=models.CharField(blank=True, choices=[('Bot_Legend_White', 'White'), ('Bot_Legend_Black', 'Black'), ('Bot_Legend_None', 'None'), ('Bot_Legend_WHPIL', 'WH PIL')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='bottom_solder_mask',
            field=models.CharField(blank=True, choices=[('Bot_SM_Green', 'Green'), ('Bot_SM_Black', 'Black'), ('Bot_SM_White', 'White'), ('Bot_SM_None', 'None'), ('Bot_SM_Red', 'Red'), ('Bot_SM_Blue', 'Blue'), ('Bot_SM_Transparent', 'Transparent'), ('Bot_SM_PCBPixture', 'PCB Pixture')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='carbon_contacts',
            field=models.CharField(blank=True, choices=[('Carbon_No', 'No'), ('Carbon_Top', 'Top'), ('Carbon_Bottom', 'Bottom'), ('Carbon_Both', 'Both')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='due_time',
            field=models.CharField(blank=True, choices=[('Due_time_1H', '1 Hour'), ('Due_time_2H', '2 Hours'), ('Due_time_3H', '3 Hours'), ('Due_time_4H', '4 Hours'), ('Due_time_5H', '5 Hours'), ('Due_time_6H', '6 Hours'), ('Due_time_7H', '7 Hours'), ('Due_time_8H', '8 Hours'), ('Due_time_9H', '9 Hours'), ('Due_time_10H', '10 Hours'), ('Due_time_12H', '12 Hours'), ('Due_time_16H', '16 Hours'), ('Due_time_24H', '24 Hours'), ('Due_time_36H', '36 Hours'), ('Due_time_48H', '48 Hours'), ('Due_time_96H', '96 Hours'), ('Due_time_120H', '120 Hours')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='edge_connector_bevelling',
            field=models.CharField(blank=True, choices=[('Bevelling_No', 'No'), ('Bevelling_STD', 'Standard'), ('Bevelling_Spl_30', 'Special 30 degrees'), ('Bevelling_Spl_20', 'Special 20 degrees'), ('Bevelling_Spl_45', 'Special 45 degrees'), ('Bevelling_Spl_60', 'Special 60 degrees')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='engineer_1',
            field=models.CharField(blank=True, choices=[('eng1_ADQ', 'ADQ'), ('eng1_JOV', 'JOV'), ('eng1_KIB', 'KIB'), ('eng1_PHH', 'PHH'), ('eng1_STB', 'STB'), ('eng1_STC', 'STC'), ('eng1_VIC', 'VIC')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='engineer_2',
            field=models.CharField(blank=True, choices=[('eng2_ADQ', 'ADQ'), ('eng2_JOV', 'JOV'), ('eng2_KIB', 'KIB'), ('eng2_PHH', 'PHH'), ('eng2_STB', 'STB'), ('eng2_STC', 'STC'), ('eng2_VIC', 'VIC')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='fai',
            field=models.CharField(blank=True, choices=[('FAI_Yes', 'Yes'), ('FAI_No', 'No')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='hole_plugging',
            field=models.CharField(blank=True, choices=[('HolePlugging_Through', 'Through'), ('HolePlugging_N/A', 'N/A'), ('HolePlugging_Blind', 'Blind'), ('HolePlugging_ThroughBlind', 'Through+Blind'), ('HolePlugging_ThroughBuried', 'Through+Buried')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='inner_layer_copper_foil',
            field=models.IntegerField(blank=True, choices=[('ILCF_12', '12 µm'), ('ILCF_18', '18 µm'), ('ILCF_35', '35 µm'), ('ILCF_70', '70 µm'), ('ILCF_105', '105 µm')], null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='inner_layer_core_thickness',
            field=models.IntegerField(blank=True, choices=[('ILCT_710', '710 µm'), ('ILCT_508', '508 µm'), ('ILCT_360', '360 µm'), ('ILCT_254', '254 µm'), ('ILCT_200', '200 µm'), ('ILCT_100', '100 µm'), ('ILCT_75', '75 µm'), ('ILCT_50', '50 µm')], null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='material_tg',
            field=models.CharField(blank=True, choices=[('tg_145_150', '145-150 ºC'), ('tg_170_180', '170-180 ºC')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qualityapp.Order'),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='outer_layer_copper_foil',
            field=models.IntegerField(blank=True, choices=[('OLCF_12', '12 µm (end +/-30 µm)'), ('OLCF_18', '18 µm (end +/-35 µm)'), ('OLCF_35', '35 µm (end +/-60 µm)'), ('OLCF_70', '70 µm (end +/-95 µm)'), ('OLCF_105', '105 µm (end +/-130 µm)')], null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='pcb_separation_method',
            field=models.CharField(blank=True, choices=[('Sep_BREAKROUTING', 'Breakrouting'), ('Sep_Vcut', 'V-cut'), ('No', 'Not Available')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='peelable_mask',
            field=models.CharField(blank=True, choices=[('SF_No', 'No'), ('Peelable_No', 'No'), ('Peelable_Top', 'Top'), ('Peelable_Bottom', 'Bottom')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='removal_nfp_allowed',
            field=models.CharField(blank=True, choices=[('Removal_NFP_Yes', 'Yes'), ('Removal_NFP_No', 'No'), ('Removal_NFP_ACP', 'ACP')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='surface_finish',
            field=models.CharField(blank=True, choices=[('SF_Any_leadfree', 'Any lead-free finish'), ('SF_HAL', 'HAL Lead-free'), ('SF_CheNiAu', 'Che Ni/Au selective'), ('SF_CheNiAu_Sel', 'Che Ni/Au sel. - large area'), ('SF_CheNiAu_bf_SM', 'Che Ni/Au before soldermask'), ('SF_CheAg', 'Che Ag'), ('SF_No', 'No')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='top_heat_sink_paste',
            field=models.CharField(blank=True, choices=[('Top_HSP_No', 'No'), ('Top_HSP_100', '100 µm'), ('Top_HSP_200', '200 µm')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='top_legend',
            field=models.CharField(blank=True, choices=[('Top_Legend_White', 'White'), ('Top_Legend_Black', 'Black'), ('Top_Legend_None', 'None'), ('Top_Legend_WHPIL', 'WH PIL')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='top_solder_mask',
            field=models.CharField(blank=True, choices=[('Top_SM_Green', 'Green'), ('Top_SM_Black', 'Black'), ('Top_SM_White', 'White'), ('Top_SM_None', 'None'), ('Top_SM_Red', 'Red'), ('Top_SM_Blue', 'Blue')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='u_via_filling',
            field=models.CharField(blank=True, choices=[('Uviafilling_1Level', '1 Level'), ('Uviafilling_No', 'No'), ('Uviafilling_2Level', '2 Level'), ('Uviafilling_3Level', '3 Level')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='venting_pattern',
            field=models.CharField(blank=True, choices=[('Venting_SinglePCB', 'Single PCB'), ('Venting_CustPanelwasteborder', 'Cust Panel waste border'), ('Venting_No', 'No'), ('Venting_Both', 'Both')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='via_filling_hole_plugging',
            field=models.CharField(blank=True, choices=[('Via_Fill_No', 'No'), ('Via_Fill_Resin', 'Resin')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Efficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.IntegerField(blank=True, null=True)),
                ('multi_layer', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='efficiency_company', to='qualityapp.Company')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qualityapp.OrderProcess')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='efficiency_service', to='qualityapp.Service')),
            ],
        ),
    ]
