# Generated by Django 2.2.6 on 2022-09-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityapp', '0009_auto_20220929_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='operator_group',
            field=models.CharField(blank=True, choices=[('GROUP_B', 'Group B'), ('GROUP_FEE', 'Group FEE'), ('CUSTOMER', 'Customer'), ('BACKOFFICE_AND_OTH', 'Backoffice and others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='operator_type',
            field=models.CharField(blank=True, choices=[('PLANET_ENG', 'Planet engineer'), ('KNOWLEDGE_LEA', 'Knowledge leaders'), ('GROUP_LEA', 'Group leaders'), ('CUSTOMER', 'Customer'), ('qualityapp_INCH', 'qualityapp incharge'), ('NETWORK_ADMI', 'Network administrator'), ('GROUP_B', 'Group B')], max_length=50, null=True),
        ),
    ]
