# Generated by Django 2.2.6 on 2022-10-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityapp', '0015_auto_20221004_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertechparameter',
            name='remarks',
        ),
        migrations.AddField(
            model_name='order',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
