# Generated by Django 2.2.6 on 2022-10-07 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("qualityapp", "0018_auto_20221006_1719"),
    ]

    operations = [
        migrations.CreateModel(
            name="NonConformity",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nc_number", models.CharField(max_length=100)),
                ("nc_remarks", models.TextField(default="")),
                ("root_cause", models.TextField(default="")),
                ("problem", models.TextField(default="")),
                ("solution", models.TextField(default="")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("nc_date", models.DateTimeField(blank=True, null=True)),
                ("category", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name="nc_category", to="qualityapp.NcCategory")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="nonconformity_company", to="qualityapp.Company")),
                ("order", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="qualityapp.Order")),
                ("sub_category", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name="nc_sub_category", to="qualityapp.NcCategory")),
            ],
        ),
        migrations.CreateModel(
            name="NonConformityDetail",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nc_detail_date", models.DateTimeField(blank=True, null=True)),
                ("non_conformity", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="qualityapp.NonConformity")),
                ("operator", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="qualityapp.Operator")),
                ("process", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="qualityapp.OrderProcess")),
            ],
        ),
    ]
