# Generated by Django 2.2.6 on 2022-11-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualityapp', '0035_userefficiencylog_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderallocationflow',
            name='allocation',
            field=models.CharField(blank=True, choices=[('pre_due_date', 'Preparation due date'), ('delivery_date', 'Delivery date'), ('systemin_time', 'System intime'), ('total_minutes', 'Total minutes'), ('order_date', 'Order date'), ('delivery_and_order_date', 'Delivery date and Order date')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='OperatorLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_in_time', models.DateTimeField(blank=True, null=True)),
                ('logged_out_time', models.DateTimeField(blank=True, null=True)),
                ('shift_id', models.CharField(blank=True, choices=[('first_shift', 'First shift'), ('second_shift', 'Second shift'), ('third_shift', 'Third shift'), ('general_shift', 'General shift')], max_length=50, null=True)),
                ('operator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='qualityapp.Operator')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveOperators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_in_time', models.DateTimeField(blank=True, null=True)),
                ('shift_id', models.CharField(blank=True, choices=[('first_shift', 'First shift'), ('second_shift', 'Second shift'), ('third_shift', 'Third shift'), ('general_shift', 'General shift')], max_length=50, null=True)),
                ('operator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='qualityapp.Operator')),
                ('reserved_order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='qualityapp.Order')),
            ],
        ),
    ]
