# Generated by Django 2.2.6 on 2022-11-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityapp', '0037_nonconformity_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userefficiencylog',
            old_name='order_status',
            new_name='order_from_status',
        ),
        migrations.AddField(
            model_name='userefficiencylog',
            name='order_to_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
