# Generated by Django 2.2.6 on 2022-12-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityapp', '0040_auto_20221130_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertechparameter',
            name='inner_layer_core_thickness',
            field=models.CharField(blank=True, choices=[('ILCT_STAN', 'Standard'), ('ILCT_710', '710 µm'), ('ILCT_508', '508 µm'), ('ILCT_360', '360 µm'), ('ILCT_254', '254 µm'), ('ILCT_200', '200 µm'), ('ILCT_100', '100 µm'), ('ILCT_75', '75 µm'), ('ILCT_50', '50 µm')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='material_tg',
            field=models.CharField(blank=True, choices=[('tg_130-140', '130-140 ºC'), ('tg_145-150', '145-150 ºC'), ('tg_170-180', '170-180 ºC')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='surface_finish',
            field=models.CharField(blank=True, choices=[('SF_Any_leadfree', 'Any lead-free finish'), ('SF_HAL', 'HAL Lead-free'), ('SF_CheNiAu', 'Che Ni/Au selective'), ('SF_CheNiAu_Sel', 'Che Ni/Au sel. - large area'), ('SF_CheNiAu_bf_SM', 'Che Ni/Au before soldermask'), ('SF_CheAg', 'Che Ag'), ('SF_No', 'No'), ('SF_HAL_Pb', 'HAL Pb')], max_length=100, null=True),
        ),
    ]
