# Generated by Django 2.2.6 on 2022-12-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityapp', '0041_auto_20221201_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertechparameter',
            name='inner_layer_core_thickness',
            field=models.CharField(blank=True, choices=[('ILCT_STD', 'Standard'), ('ILCT_710', '710 µm'), ('ILCT_508', '508 µm'), ('ILCT_360', '360 µm'), ('ILCT_254', '254 µm'), ('ILCT_200', '200 µm'), ('ILCT_100', '100 µm'), ('ILCT_75', '75 µm'), ('ILCT_50', '50 µm')], max_length=100, null=True),
        ),
    ]
