# Generated by Django 2.2.6 on 2022-12-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityapp', '0046_skillmatrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='efficiency',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nccategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderflowmapping',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skillmatrix',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='operator',
            name='company_ids',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
