# Generated by Django 2.2.6 on 2023-01-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityapp', '0048_auto_20221229_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertechparameter',
            name='bottom_legend',
            field=models.CharField(blank=True, choices=[('Bot_Legend_White', 'White'), ('Bot_Legend_Black', 'Black'), ('Bot_Legend_None', 'None'), ('Bot_Legend_WHPIL', 'WH PIL'), ('Bot_Legend_Yellow', 'Yellow')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='carbon_contacts',
            field=models.CharField(blank=True, choices=[('Carbon_Not_Available', 'Not Available'), ('Carbon_No', 'No'), ('Carbon_Top', 'Top'), ('Carbon_Bottom', 'Bottom'), ('Carbon_Both', 'Both')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='edge_connector_bevelling',
            field=models.CharField(blank=True, choices=[('Bevelling_No', 'No'), ('Bevelling_0', '0'), ('Bevelling_Special', 'Special'), ('Bevelling_STD', 'Standard'), ('Bevelling_Spl_30', 'Special 30 degrees'), ('Bevelling_Spl_20', 'Special 20 degrees'), ('Bevelling_Spl_45', 'Special 45 degrees'), ('Bevelling_Spl_60', 'Special 60 degrees')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='inner_layer_copper_foil',
            field=models.CharField(blank=True, choices=[('ILCF_12', '12 µm'), ('ILCF_18', '18 µm'), ('ILCF_35', '35 µm'), ('ILCF_70', '70 µm'), ('ILCF_105', '105 µm'), ('ILCF_0', '0')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='inner_layer_core_thickness',
            field=models.CharField(blank=True, choices=[('ILCT_STD', 'Standard'), ('ILCT_710', '710 µm'), ('ILCT_508', '508 µm'), ('ILCT_360', '360 µm'), ('ILCT_254', '254 µm'), ('ILCT_200', '200 µm'), ('ILCT_100', '100 µm'), ('ILCT_75', '75 µm'), ('ILCT_50', '50 µm'), ('ILCT_LT_50', '< 50 micron'), ('ILCT_GT_100', '>=100 micron'), ('ILCT_GT_200', '>=200 micron'), ('ILCT_GT_254', '>=254 micron'), ('ILCT_GT_360', '>=360 micron'), ('ILCT_GT_50', '>=50 micron'), ('ILCT_GT_508', '>=508 micron'), ('ILCT_GT_710', '>=710 micron'), ('ILCT_GT_75', '>=75 micron')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='material_tg',
            field=models.CharField(blank=True, choices=[('tg_130-140', '130-140 ºC'), ('tg_145-150', '145-150 ºC'), ('tg_170-180', '170-180 ºC'), ('tg_210', '> 210 C ºC'), ('tg_100', '100°C'), ('tg_280', '280 ºC')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='outer_layer_copper_foil',
            field=models.CharField(blank=True, choices=[('OLCF_12', '12 µm (end +/-30 µm)'), ('OLCF_18', '18 µm (end +/-35 µm)'), ('OLCF_35', '35 µm (end +/-60 µm)'), ('OLCF_70', '70 µm (end +/-95 µm)'), ('OLCF_105', '105 µm (end +/-130 µm)'), ('OLCF_0', '0')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='peelable_mask',
            field=models.CharField(blank=True, choices=[('Peelable_Not_Available', 'Not Available'), ('Peelable_No', 'No'), ('Peelable_Top', 'Top'), ('Peelable_Bottom', 'Bottom'), ('Peelable_Top_Bottom', 'Top+Bottom')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='surface_finish',
            field=models.CharField(blank=True, choices=[('SF_Any_leadfree', 'Any lead-free finish'), ('SF_HAL', 'HAL Lead-free'), ('SF_CheNiAu', 'Che Ni/Au selective'), ('SF_CheNiAu_Sel', 'Che Ni/Au sel. - large area'), ('SF_CheNiAu_bf_SM', 'Che Ni/Au before soldermask'), ('SF_CheAg', 'Che Ag'), ('SF_No', 'No'), ('SF_HAL_Pb', 'HAL Pb'), ('SF_Che_Sn', 'Che Sn'), ('SF_CheNiAu_if', 'Che Ni/Au selectif'), ('SF_CheNiAu_overall', 'Che Ni/Au overall')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='top_legend',
            field=models.CharField(blank=True, choices=[('Top_Legend_White', 'White'), ('Top_Legend_Black', 'Black'), ('Top_Legend_None', 'None'), ('Top_Legend_WHPIL', 'WH PIL'), ('Top_Legend_Yellow', 'Yellow')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='top_solder_mask',
            field=models.CharField(blank=True, choices=[('Top_SM_Green', 'Green'), ('Top_SM_Black', 'Black'), ('Top_SM_White', 'White'), ('Top_SM_None', 'None'), ('Top_SM_Red', 'Red'), ('Top_SM_Blue', 'Blue'), ('Top_SM_Transparent', 'Transparent'), ('Top_SM_PCB_PIXture', 'PCB PIXture')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='via_filling_hole_plugging',
            field=models.CharField(blank=True, choices=[('Via_Fill_No', 'No'), ('Via_Fill_Resin', 'Resin'), ('Via_Fill_Bottom', 'Bottom'), ('Via_Fill_Top', 'Top'), ('Via_Fill_Soldermask', 'Soldermask')], max_length=100, null=True),
        ),
    ]
