# Generated by Django 2.2.6 on 2023-01-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityapp', '0051_auto_20230106_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='show_own_records_only',
            field=models.BooleanField(default=False),
        ),
    ]
