# Generated by Django 2.2.6 on 2023-02-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityapp', '0058_auto_20230206_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderexception',
            name='is_si_file',
            field=models.BooleanField(default=False),
        ),
    ]
