# Generated by Django 2.2.6 on 2023-02-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityapp', '0060_technicalhelp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertechparameter',
            name='engineer_1',
            field=models.CharField(blank=True, choices=[('eng1_JOV', 'JOV'), ('eng1_KIB', 'KIB'), ('eng1_PHH', 'PHH'), ('eng1_STB', 'STB'), ('eng1_VIC', 'VIC'), ('eng1_MIS', 'MST')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='engineer_2',
            field=models.CharField(blank=True, choices=[('eng2_JOV', 'JOV'), ('eng2_KIB', 'KIB'), ('eng2_PHH', 'PHH'), ('eng2_STB', 'STB'), ('eng2_VIC', 'VIC'), ('eng2_MIS', 'MST')], max_length=100, null=True),
        ),
    ]
