# Generated by Django 2.2.6 on 2023-02-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityapp', '0067_auto_20230222_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='userefficiencylog',
            name='operator_shift',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
