# Generated by Django 2.2.6 on 2023-03-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityapp', '0070_auto_20230316_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_experience', models.CharField(choices=[('6_month', '6 months since joining'), ('1_year', '1 year since joining'), ('2_year', '2 years since joining')], max_length=100, null=True)),
                ('target_efficiency', models.IntegerField(blank=True, null=True)),
                ('minimum_efficiency', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
