# Generated by Django 2.2.6 on 2023-03-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualityapp', '0074_auto_20230330_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyparameter',
            name='int_exc_cc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyparameter',
            name='int_exc_from',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyparameter',
            name='int_exc_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
