# Generated by Django 2.2.6 on 2023-04-03 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0005_auto_20221206_1907'),
        ('qualityapp', '0075_auto_20230330_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformitydetail',
            name='audit_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auditlog.Auditlog'),
        ),
    ]
