# Generated by Django 3.2.10 on 2022-03-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0002_auditaction_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='action_by',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='AuditAction',
        ),
        migrations.DeleteModel(
            name='Auditlog',
        ),
    ]
