# Generated by Django 3.2.10 on 2022-05-04 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0048_merge_20220504_1316'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, null=True)),
                ('coda_file_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('message', models.CharField(max_length=500, null=True)),
                ('invoice_no', models.CharField(max_length=200, null=True)),
                ('ec_customer_id', models.IntegerField(blank=True, null=True)),
                ('ec_customer_name', models.CharField(max_length=200, null=True)),
                ('bank_account_no', models.CharField(max_length=200, null=True)),
                ('bank_name', models.CharField(max_length=200, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.invoice')),
            ],
        ),
    ]
