# Generated by Django 3.2.10 on 2022-05-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymentbrowserunmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codafile',
            name='compared_xml_string',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='codafile',
            name='xml_string',
            field=models.TextField(null=True),
        ),
    ]
