# Generated by Django 3.2.10 on 2022-05-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20220506_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codafile',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
