# Generated by Django 3.2.10 on 2022-05-18 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_auto_20220510_1109'),
        ('payment', '0006_auto_20220518_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codacustomermapping',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='codacustomermapping',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='codacustomermapping',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customer'),
        ),
    ]
