# Generated by Django 3.2.10 on 2022-05-20 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_auto_20220510_1109'),
        ('payment', '0007_auto_20220518_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codatransaction',
            name='ec_customer_id',
        ),
        migrations.AddField(
            model_name='codatransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customer'),
        ),
    ]
