# Generated by Django 3.2.10 on 2022-05-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20220520_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='codatransaction',
            name='ec_customer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
