# Generated by Django 3.2.10 on 2022-05-20 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0054_remove_invoice_currency_customer_value'),
        ('base', '0007_alter_codetable_is_deleted'),
        ('customer', '0021_auto_20220510_1109'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0009_codatransaction_ec_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('paid_on', models.DateTimeField(auto_now_add=True)),
                ('currency_rate', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('currency_total_amount', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('payment_mode', models.CharField(choices=[('bank', 'Bank'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('credit_card', 'Credit card'), ('paypal', 'Paypal'), ('BT', 'BT'), ('COD', 'COD'), ('CBP', 'CBP')], max_length=100, null=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.currency')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
                ('transfer_type', models.CharField(max_length=50, null=True)),
                ('reference', models.CharField(max_length=50, null=True)),
                ('ref_document_do', models.CharField(max_length=50, null=True)),
                ('payment_difference_type', models.CharField(choices=[('outstanding', 'Outstanding'), ('bank_charges', 'Bank Charges'), ('discount', 'Discount'), ('write_off', 'Write off'), ('over_paid', 'OverPaid'), ('close', 'Close')], max_length=100, null=True)),
                ('payment_date', models.DateTimeField(null=True)),
                ('balance_on_date', models.IntegerField(null=True)),
                ('remark', models.TextField(default='')),
                ('username', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('currency_amount', models.IntegerField(null=True)),
                ('currency_balance_on_date', models.IntegerField(null=True)),
                ('paid_on', models.DateTimeField(auto_now_add=True)),
                ('currency_rate', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('currency_total_amount', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.currency')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.invoice')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.payment')),
            ],
        ),
    ]
