# Generated by Django 3.2.10 on 2022-05-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_payment_paymentregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentregistration',
            name='paid_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
