# Generated by Django 3.2.10 on 2022-05-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_alter_paymentregistration_paid_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentregistration',
            name='balance_on_date',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='paymentregistration',
            name='currency_balance_on_date',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True),
        ),
    ]
