# Generated by Django 3.2.10 on 2022-01-31 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
