# Generated by Django 3.2.10 on 2022-02-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_currencyrate_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codetable',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
