# Generated by Django 3.2.10 on 2022-02-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_codetable_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codetable',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
