# Generated by Django 3.2.10 on 2022-02-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_codetable_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codetable',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
