# Generated by Django 2.2.6 on 2022-12-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assign_to',
        ),
        migrations.AddField(
            model_name='task',
            name='assign_to',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
