# Generated by Django 2.2.6 on 2022-12-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20221215_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='general',
            field=models.BooleanField(default=False, verbose_name='General'),
        ),
    ]
