# Generated by Django 2.2.6 on 2022-12-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_message_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Is delete'),
        ),
    ]
