# Generated by Django 2.2.6 on 2022-12-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20221229_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assign_to',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
