# Generated by Django 2.2.6 on 2022-09-08 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Currency name')),
                ('symbol', models.CharField(max_length=3, verbose_name='Currency symbol')),
                ('is_base', models.BooleanField(default=False, verbose_name='Base currency')),
                ('is_deleted', models.BooleanField(verbose_name='Deleted')),
            ],
        ),
        migrations.CreateModel(
            name='DMI_queries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Report title')),
                ('descr', models.CharField(blank=True, max_length=250, null=True, verbose_name='Report description')),
                ('report_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Report code')),
                ('report_sql', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Report SQL')),
                ('report_para', models.CharField(blank=True, max_length=300, null=True, verbose_name='Report Parameters')),
                ('url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Url')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('prefix', models.CharField(blank=True, help_text='Either put fixed characters or an expression', max_length=20, null=True, verbose_name='Prefix')),
                ('length', models.IntegerField(verbose_name='Length')),
                ('increment', models.IntegerField(default=1, verbose_name='Increment by')),
                ('nextint', models.IntegerField(default=1, verbose_name='Next integer')),
                ('nextnum', models.CharField(max_length=30, verbose_name='Next number')),
            ],
        ),
        migrations.CreateModel(
            name='SysParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para_code', models.CharField(max_length=60, verbose_name='Parameter code')),
                ('descr', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('para_value', models.CharField(blank=True, max_length=1000, verbose_name='Parameter value')),
                ('para_group', models.CharField(blank=True, max_length=30, null=True, verbose_name='Parameter Group')),
                ('for_system', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('code', models.CharField(blank=True, max_length=15, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('schedule', models.CharField(blank=True, help_text='Recur Daily, Weekly, Monthly, Yearly, Specific Date', max_length=500, null=True, verbose_name='How often to be done')),
                ('pattern', models.CharField(blank=True, max_length=100, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_run_result', models.CharField(blank=True, max_length=500, null=True)),
                ('notification_email', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'processing')], default='pending', max_length=20, null=True)),
                ('is_running', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UISettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('table_index', models.IntegerField()),
                ('col_settings', models.CharField(max_length=2000, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=12, verbose_name='Release version')),
                ('note', models.TextField(verbose_name='Release note')),
                ('created_on', models.DateTimeField(verbose_name='Release date')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='View name')),
                ('url', models.CharField(max_length=500, verbose_name='View url')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.DMI_queries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Currency factor')),
                ('reference_date', models.DateTimeField(verbose_name='Reference date')),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency', to='base.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='AppReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('production', 'Production'), ('inventory', 'Inventory'), ('maintenances', 'Maintenances'), ('hrm', 'HRM'), ('eda', 'EDA')], max_length=50)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.DMI_queries')),
            ],
        ),
    ]
