# Generated by Django 2.2.6 on 2022-10-04 14:00

import attachment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Remark_Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('uid', models.CharField(default=attachment.models.get_uid, max_length=50)),
                ('object_id', models.IntegerField()),
                ('url', models.FileField(upload_to=attachment.models.update_filename)),
                ('title', models.CharField(default='', max_length=150)),
                ('subject', models.CharField(default='', max_length=50)),
                ('source_doc', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('size', models.IntegerField(default=0)),
                ('ip_addr', models.CharField(default='', max_length=45)),
                ('deleted', models.BooleanField(default=False)),
                ('checksum', models.CharField(default='', max_length=45)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('doc_type', models.CharField(choices=[('general', 'General'), ('invoice', 'Invoice'), ('order', 'Order')], default='gen', max_length=20, verbose_name='Doc Type')),
                ('is_public', models.BooleanField(default=False)),
                ('file_type', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='attachment.FileType', verbose_name='File type')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.IntegerField(blank=True, null=True, verbose_name='ID of the object')),
                ('remark', models.TextField(blank=True, null=True)),
                ('remark_type', models.CharField(choices=[('normal', 'Normal'), ('rejection', 'Rejection'), ('customer', 'Customer')], max_length=10, verbose_name='Remark type')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('comment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.CommentType')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
