# Generated by Django 2.2.6 on 2023-04-10 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_base_attachment_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='prep_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Operator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remark',
            name='prep_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
