# Generated by Django 2.2.6 on 2023-05-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remark_prep_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_attachment',
            name='is_url',
            field=models.BooleanField(default=False),
        ),
    ]
