# Generated by Django 2.2.6 on 2022-11-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rolegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolegroup',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
