# Generated by Django 2.2.6 on 2023-01-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rolegroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolegroup',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
