# Generated by Django 3.2.10 on 2021-12-09 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Menu name')),
                ('url', models.CharField(max_length=1000, verbose_name='Url')),
                ('icon', models.CharField(max_length=500, verbose_name='Icon')),
                ('sequence', models.IntegerField(default=0, verbose_name='Sequence')),
                ('is_active', models.BooleanField(default=True)),
                ('menu_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Menu Code')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.mainmenu')),
            ],
        ),
    ]
