# Generated by Django 3.2.10 on 2021-12-10 11:22

import accounts.models
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('theme', models.CharField(blank=True, max_length=15, null=True, verbose_name='Color')),
                ('display_row', models.IntegerField(blank=True, null=True, verbose_name='Display row')),
                ('default_page', models.TextField(blank=True, max_length=250, null=True, verbose_name='Default page loaded after login')),
                ('profile_image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=accounts.models.get_profile_image_name)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
