# Generated by Django 3.2.10 on 2021-12-28 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_contentpermission_grouppermission_pagepermission_usergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Code')),
                ('has_state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_company', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.country', verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending')], max_length=50)),
                ('outstanding_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency_outstanding_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('invoice_created_on', models.DateTimeField(auto_now_add=True)),
                ('invoice_due_date', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduler_name', models.CharField(max_length=200, verbose_name='Scheduler Name')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ManyToManyField(to='accounts.Invoice')),
                ('scheduler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.scheduler')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(blank=True, choices=[('call', 'Call'), ('chat', 'Chat'), ('offline_message', 'Offline message'), ('ticket', 'Ticket'), ('plan_follow_up', 'Plan Follow up')], max_length=100, null=True)),
                ('action_date', models.DateTimeField()),
                ('summary', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment', models.TextField(default='')),
                ('is_legal_action', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('call_due', 'Call due'), ('finished', 'Finished')], max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('scheduler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.scheduler')),
            ],
        ),
    ]
