# Generated by Django 3.2.10 on 2022-01-06 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_collectionaction_country_customer_invoice_scheduler_scheduleritem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionaction',
            name='status',
        ),
        migrations.AddField(
            model_name='scheduler',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('call_due', 'Call due'), ('call_done', 'Call done'), ('finished', 'Finished'), ('legal_action', 'Legal Action')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='total_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduler_invoices', to='accounts.invoice'),
        ),
        migrations.AlterField(
            model_name='collectionaction',
            name='scheduler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_scheduler', to='accounts.scheduler'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='scheduleritem',
            name='invoice',
            field=models.ManyToManyField(related_name='total_invoices', to='accounts.Invoice'),
        ),
        migrations.AlterField(
            model_name='scheduleritem',
            name='scheduler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduler_item', to='accounts.scheduler'),
        ),
    ]
