# Generated by Django 3.2.10 on 2022-01-24 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20220106_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_company',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='total_invoice',
        ),
        migrations.AddField(
            model_name='collectionaction',
            name='next_action_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionaction',
            name='next_action_type',
            field=models.CharField(blank=True, choices=[('call', 'Call'), ('chat', 'Chat'), ('offline_message', 'Offline message'), ('ticket', 'Ticket'), ('plan_follow_up', 'Plan Follow up')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collectionaction',
            name='next_attachment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='collectionaction',
            name='next_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collectionaction',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='is_legal_action',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduleritem',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduler_customer', to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='collectionaction',
            name='action_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectionaction',
            name='scheduler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduler', to='accounts.scheduler'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('call_due', 'Call due'), ('call_done', 'Call done'), ('finished', 'Finished'), ('legal_action', 'Legal Action')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduleritem',
            name='invoice',
            field=models.ManyToManyField(related_name='scheduler_invoice', to='accounts.Invoice'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usergroup', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
