# Generated by Django 3.2.10 on 2022-01-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220124_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='company',
        ),
        migrations.RemoveField(
            model_name='scheduleritem',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='scheduleritem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='scheduleritem',
            name='scheduler',
        ),
        migrations.DeleteModel(
            name='CollectionAction',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Scheduler',
        ),
        migrations.DeleteModel(
            name='SchedulerItem',
        ),
    ]
