# Generated by Django 2.2.6 on 2022-11-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20221107_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysparameter',
            name='descr',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
    ]
