# Generated by Django 2.2.6 on 2022-12-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20221107_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='remark_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('rejection', 'Rejection'), ('customer', 'Customer'), ('Cus_rema', 'Customer Remarks'), ('Cum_rema', 'Customer CAM Remarks')], max_length=10, verbose_name='Remark type'),
        ),
    ]
