# Generated by Django 2.2.6 on 2023-01-23 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qualityapp', '0054_auto_20230119_1056'),
        ('base', '0007_base_attachment_baseattachmenttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_attachment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='qualityapp.Company'),
        ),
        migrations.AlterField(
            model_name='base_attachment',
            name='object_id',
            field=models.IntegerField(),
        ),
    ]
