# Generated by Django 2.2.6 on 2023-03-27 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0001_initial'),
        ('base', '0008_auto_20230123_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_attachment',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attachment.Tag'),
        ),
    ]
