# Generated by Django 2.2.6 on 2023-04-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20230410_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='prep_section',
            field=models.CharField(blank=True, choices=[('schematic', 'Schematic'), ('footprint', 'Footprint'), ('placement', 'Placement'), ('routing', 'Routing'), ('gerber_release', 'Gerber Release'), ('analysis', 'Analysis'), ('incoming', 'Incoming'), ('BOM_incoming', 'BOM incoming'), ('SI', 'SI'), ('SICC', 'SICC'), ('BOM_CC', 'BOM CC'), ('FQC', 'FQC'), ('panel', 'Panel'), ('upload_panel', 'Upload Panel'), ('cancel', 'Cancel'), ('exception', 'Exception'), ('ppa_exception', 'PPA Exception'), ('finished', 'Order Finish')], max_length=50, null=True),
        ),
    ]
