# Generated by Django 2.2.6 on 2020-03-25 12:19

import attachment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attachment', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMI_queries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Report title')),
                ('descr', models.CharField(blank=True, max_length=250, null=True, verbose_name='Report description')),
                ('report_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Report code')),
                ('report_sql', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Report SQL')),
                ('report_para', models.CharField(blank=True, max_length=300, null=True, verbose_name='Report Parameters')),
                ('url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Url')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('prefix', models.CharField(blank=True, help_text='Either put fixed characters or an expression', max_length=20, null=True, verbose_name='Prefix')),
                ('length', models.IntegerField(verbose_name='Length')),
                ('increment', models.IntegerField(default=1, verbose_name='Increment by')),
                ('nextint', models.IntegerField(default=1, verbose_name='Next integer')),
                ('nextnum', models.CharField(max_length=30, verbose_name='Next number')),
            ],
        ),
        migrations.CreateModel(
            name='SysParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para_code', models.CharField(max_length=60, verbose_name='Parameter code')),
                ('descr', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('para_value', models.CharField(max_length=1000, verbose_name='Parameter value')),
                ('para_group', models.CharField(blank=True, max_length=30, null=True, verbose_name='Parameter Group')),
            ],
        ),
        migrations.CreateModel(
            name='UISettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('table_index', models.IntegerField()),
                ('col_settings', models.CharField(max_length=500, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Remark_Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('uid', models.CharField(default=attachment.models.get_uid, max_length=50)),
                ('object_id', models.IntegerField()),
                ('url', models.FileField(upload_to=attachment.models.update_filename)),
                ('title', models.CharField(default='', max_length=50)),
                ('subject', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('size', models.IntegerField(default=0)),
                ('ip_addr', models.CharField(default='', max_length=45)),
                ('deleted', models.BooleanField(default=False)),
                ('checksum', models.CharField(default='', max_length=45)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('general', 'General'), ('invoice', 'Invoice'), ('order', 'Order')], default='gen', max_length=20, verbose_name='Doc Type')),
                ('is_public', models.BooleanField(default=False)),
                ('file_type', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='attachment.FileType', verbose_name='File type')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.IntegerField(blank=True, null=True, verbose_name='ID of the object')),
                ('remark', models.TextField(blank=True, null=True)),
                ('remark_type', models.CharField(choices=[('normal', 'Normal'), ('rejection', 'Rejection')], max_length=10, verbose_name='Remark type')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=12, verbose_name='Release version')),
                ('note', models.TextField(verbose_name='Release note')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='View name')),
                ('url', models.CharField(max_length=500, verbose_name='View url')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.DMI_queries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20)),
                ('expire_on', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(choices=[('user', 'User')], max_length=50)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.DMI_queries')),
            ],
        ),
    ]
