from django.conf.urls import url

from . import views

app_name = "hrm"

urlpatterns = [
    url(r"^leave_types/$", views.leave_types, name="leave_types"),
    url(r"^leave_type_search/$", views.leave_type_search, name="leave_type_search"),
    url(r"^get_leave_type/$", views.get_leave_type, name="get_leave_type"),
    url(r"^leave_type_save/$", views.leave_type_save, name="leave_type_save"),
    url(r"^leave_type_delete/$", views.leave_type_delete, name="leave_type_delete"),
    url(r"^leaves_allocation/$", views.leaves_allocation, name="leaves_allocation"),
    url(r"^leaves_allocation_search/$", views.leaves_allocation_search, name="leaves_allocation_search"),
    url(r"^leaves_allocation_delete/$", views.leaves_allocation_delete, name="leaves_allocation_delete"),
    url(r"^leaves_allocation_save/$", views.leaves_allocation_save, name="leaves_allocation_save"),
    url(r"^get_leave_days/$", views.get_leave_days, name="get_leave_days"),
    url(r"^leaves_view/$", views.leaves_view, name="leaves_view"),
    url(r"^leaves_search/([^/]+)/$", views.leaves_search, name="leaves_search"),
    url(r"^my_leaves_save/$", views.my_leaves_save, name="my_leaves_save"),
    url(r"^get_leave_allocation/$", views.get_leave_allocation, name="get_leave_allocation"),
    url(r"^leave_cancel/$", views.leave_cancel, name="leave_cancel"),
    url(r"^all_leaves/$", views.all_leaves, name="all_leaves"),
    url(r"^leave_approve/$", views.leave_approve, name="leave_approve"),
    url(r"^leave_reject/$", views.leave_reject, name="leave_reject"),
    url(r"^all_leaves_delete/$", views.all_leaves_delete, name="all_leaves_delete"),
    url(r"^employee/$", views.employee, name="employee"),
    url(r"^employee/(\d+)/$", views.employee, name="employee"),
    url(r"^holiday/$", views.holiday, name="holiday"),
    url(r"^holiday/(\d+)/$", views.holiday, name="holiday"),
    url(r"^leaves_allocation_get/$", views.leaves_allocation_get, name="leaves_allocation_get"),
    url(r"^summary_leave_mail/([^/]+)/$", views.summary_leave_mail, name="summary_leave_mail"),
    url(r"^holidays/$", views.holidays, name="holidays"),
    url(r"^holidays_search/$", views.holidays_search, name="holidays_search"),
    url(r"^holidays_del/$", views.holidays_del, name="holidays_del"),
    url(r"^check_working_day/$", views.check_working_day, name="check_working_day"),
    url(r"^import_holiday/$", views.import_holiday, name="import_holiday"),
    url(r"^export_holiday/$", views.export_holiday, name="export_holiday"),
    url(r"^get_holiday/$", views.get_holiday, name="get_holiday"),
    url(r"^leaves_report/$", views.leaves_report, name="leaves_report"),
    url(r"^leaves_export/$", views.leaves_export, name="leaves_export"),
    url(r"^get_all_leaves_calendar/$", views.get_all_leaves_calendar, name="get_all_leaves_calendar"),
    url(r"^qualification_type_search/$", views.qualification_type_search, name="qualification_type_search"),
    url(r"^qualifications_type/$", views.qualifications_type, name="qualifications_type"),
    url(r"^qualification_type/(\d+)/$", views.qualification_type, name="qualification_type"),
    url(r"^qualification_type_delete/$", views.qualification_type_delete, name="qualification_type_delete"),
    url(r"^get_qualification_type/$", views.get_qualification_type, name="get_qualification_type"),
    url(r"^qualification_type_save/$", views.qualification_type_save, name="qualification_type_save"),
    url(r"^employee_leaves_search/([^/]+)/$", views.employee_leaves_search, name="employee_leaves_search"),
]
