# Generated by Django 3.2.10 on 2022-02-01 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_last_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='company',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='company',
            new_name='customer',
        ),
    ]
