# Generated by Django 3.2.10 on 2022-02-01 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_currencyrate_created_on'),
        ('customer', '0006_alter_address_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='invoice_lang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_language', to='base.codetable'),
            preserve_default=False,
        ),
    ]
