# Generated by Django 3.2.10 on 2022-03-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20220211_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
