# Generated by Django 3.2.10 on 2022-03-24 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_codetable_is_deleted'),
        ('customer', '0013_alter_customer_last_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='invoice_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_language', to='base.codetable'),
        ),
    ]
