# Generated by Django 3.2.10 on 2022-03-25 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_customer_invoice_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_vat_verified',
        ),
    ]
