# Generated by Django 3.2.10 on 2022-03-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_remove_customer_is_vat_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_vat_verified',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
