# Generated by Django 3.2.10 on 2022-04-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_customer_is_vat_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='root_company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
