# Generated by Django 3.2.10 on 2022-04-20 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_customer_root_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='root_company_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='root_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customer'),
        ),
    ]
