# Generated by Django 3.2.10 on 2022-04-21 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_auto_20220420_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='hand_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handling_company', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='short_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='root_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='root_comp', to='customer.customer'),
        ),
    ]
