# Generated by Django 3.2.10 on 2022-04-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_auto_20220421_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='hand_company',
            new_name='is_handling',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='root_company',
            new_name='is_root',
        ),
    ]
