# Generated by Django 3.2.10 on 2022-05-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_auto_20220421_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='invoice_delivery',
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_credit_limit',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='invo_delivery',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
