# Generated by Django 2.2.6 on 2022-12-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0003_auto_20221130_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='prep_time',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
    ]
