# Generated by Django 2.2.6 on 2022-09-14 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('post_office', '0008_attachment_headers'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('group', models.CharField(blank=True, choices=[('sales', 'Sales'), ('purchasing', 'Purchasing'), ('inventory', 'Inventory')], max_length=30, null=True)),
                ('action', models.CharField(blank=True, choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('started', 'Started'), ('completed', 'Completed'), ('remark', 'Remark'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=30, null=True)),
                ('subject', models.CharField(max_length=250, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='SubscribeNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_email', models.BooleanField(default=False)),
                ('in_system', models.BooleanField(default=False)),
                ('by_sms', models.BooleanField(default=False)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='messaging.NotificationEvent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscribenotification_subscribe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('content', models.CharField(max_length=600)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='sms_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='messaging.SMSTemplate'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='post_office.EmailTemplate'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250, verbose_name='Subject')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Body')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('type', models.CharField(blank=True, choices=[('so_ship_delay', 'SO shipment due'), ('po_ship_delay', 'PO shipment due'), ('mo_delay', 'MO due'), ('maintenance_delay', 'Maintenance due'), ('comment_mension', 'Mension in comment'), ('product_reorder', 'Product reorder level'), ('product_review', 'Product review')], max_length=20, null=True, verbose_name='Notification type')),
                ('entity_id', models.IntegerField(blank=True, null=True, verbose_name='Model P.K related to notification type')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('read_on', models.DateTimeField(blank=True, null=True)),
                ('push_notify', models.BooleanField(default=False)),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_subscribe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250, verbose_name='Subject')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parent_msg_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='messaging.Messaging')),
            ],
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='messaging.Messaging', verbose_name='Message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
        ),
    ]
