# Generated by Django 2.2.6 on 2023-05-30 11:35

import attachment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachment', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Task type')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=500, null=True, verbose_name='Icon')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task_Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=270)),
                ('uid', models.CharField(default=attachment.models.get_uid, max_length=50)),
                ('object_id', models.IntegerField()),
                ('url', models.FileField(max_length=270, upload_to=attachment.models.update_filename)),
                ('title', models.CharField(default='', max_length=150)),
                ('subject', models.CharField(default='', max_length=50)),
                ('source_doc', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('size', models.IntegerField(default=0)),
                ('ip_addr', models.CharField(default='', max_length=45)),
                ('deleted', models.BooleanField(default=False)),
                ('checksum', models.CharField(default='', max_length=45)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('doc_type', models.CharField(choices=[('general', 'General'), ('invoice', 'Invoice'), ('order', 'Order')], default='gen', max_length=20, verbose_name='Doc Type')),
                ('is_public', models.BooleanField(default=False)),
                ('file_type', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='attachment.FileType', verbose_name='File type')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('entity_id', models.IntegerField(blank=True, null=True, verbose_name='ID of the object')),
                ('related_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Related to')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due date')),
                ('status', models.CharField(blank=True, choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=40, null=True)),
                ('priority', models.CharField(blank=True, choices=[('low', 'Normal'), ('medium', 'Warning'), ('high', 'Critical'), ('urgent', 'Urgent')], default='low', max_length=40, null=True)),
                ('assign_to', models.CharField(blank=True, max_length=4000, null=True)),
                ('email_notification', models.BooleanField(default=False, verbose_name='Email notification')),
                ('private', models.BooleanField(default=False, verbose_name='Private task')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('due_mail_sent_time', models.DateTimeField(null=True)),
                ('reminder_on', models.DateTimeField(blank=True, null=True)),
                ('reminder_on_text', models.CharField(blank=True, max_length=50, null=True)),
                ('has_reminder_sent', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('general', models.BooleanField(default=False, verbose_name='General')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Is delete')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='task.TaskType', verbose_name='Task type')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is read')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('read_on', models.DateTimeField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False, verbose_name='Is delete')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task.Task')),
            ],
        ),
    ]
