# Generated by Django 2.2.6 on 2020-03-27 12:29

import attachment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attachment', '0001_initial'),
        ('accounts', '0002_auto_20200326_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('uid', models.CharField(default=attachment.models.get_uid, max_length=50)),
                ('object_id', models.IntegerField()),
                ('url', models.FileField(upload_to=attachment.models.update_filename)),
                ('title', models.CharField(default='', max_length=50)),
                ('subject', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('size', models.IntegerField(default=0)),
                ('ip_addr', models.CharField(default='', max_length=45)),
                ('deleted', models.BooleanField(default=False)),
                ('checksum', models.CharField(default='', max_length=45)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('general', 'General'), ('invoice', 'Invoice'), ('order', 'Order')], default='gen', max_length=20, verbose_name='Doc Type')),
                ('is_public', models.BooleanField(default=False)),
                ('file_type', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='attachment.FileType', verbose_name='File type')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
