# Generated by Django 2.2.6 on 2022-09-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_ids',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ec_user',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='group_type',
            field=models.CharField(blank=True, choices=[(1, 'Planet engineer'), (2, 'Knowledge leaders'), (3, 'Group leaders'), (4, 'Customer'), (5, 'PWS incharge'), (6, 'Network administrator'), (7, 'Group B')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='permanent_shift',
            field=models.CharField(blank=True, choices=[(1, 'First shift'), (2, 'Second shift'), (3, 'Third shift'), (4, 'General shift')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shift',
            field=models.CharField(blank=True, choices=[(1, 'First shift'), (2, 'Second shift'), (3, 'Third shift'), (4, 'General shift')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_group',
            field=models.CharField(blank=True, choices=[(1, 'Group B'), (2, 'Group FEE'), (3, 'Customer'), (4, 'Backoffice and others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Planet engineer'), (2, 'Knowledge leaders'), (3, 'Group leaders'), (4, 'Customer'), (5, 'PWS incharge'), (6, 'Network administrator'), (7, 'Group B')], null=True, verbose_name='User type'),
        ),
    ]
