# Generated by Django 2.2.6 on 2023-02-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20230201_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpermission',
            name='is_customer_user',
        ),
        migrations.RemoveField(
            model_name='contentpermission',
            name='is_operator',
        ),
    ]
