# Generated by Django 2.2.6 on 2023-02-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20230201_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='is_customer_user',
            field=models.BooleanField(default=False, verbose_name='View customer user'),
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='is_operator',
            field=models.BooleanField(default=False, verbose_name='View operator'),
        ),
    ]
