# Generated by Django 3.2.10 on 2022-01-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20220131_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
