# Generated by Django 3.2.10 on 2022-02-01 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_currencyrate_created_on'),
        ('customer', '0003_alter_customer_last_order_date'),
        ('sales', '0004_scheduleritem_is_legal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='company',
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_customer', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='hand_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_hand_company', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_invoice_type', to='base.codetable'),
        ),
        migrations.AlterField(
            model_name='invoiceorder',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoiceorder_invoice', to='sales.invoice'),
        ),
        migrations.AlterField(
            model_name='scheduleritem',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduleritem_customer', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='scheduleritem',
            name='scheduler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduleritem_scheduler', to='sales.scheduler'),
        ),
    ]
