# Generated by Django 3.2.10 on 2022-02-01 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_currencyrate_created_on'),
        ('customer', '0006_alter_address_customer'),
        ('sales', '0006_auto_20220201_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionaction',
            name='customer',
            field=models.ForeignKey(default=2858, on_delete=django.db.models.deletion.PROTECT, related_name='collectionaction_customer', to='customer.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collectionaction',
            name='action_status',
            field=models.CharField(blank=True, choices=[('due', 'Due'), ('done', 'Done')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collectionaction',
            name='scheduler_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_scheduler', to='sales.scheduleritem'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='country_of_origin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='last_rem_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='packing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='service_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_status', to='base.codetable'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='trans_port_serivice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
