# Generated by Django 3.2.10 on 2022-02-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_invoice_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_iddress_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_legal',
            field=models.BooleanField(default=False),
        ),
    ]
