# Generated by Django 3.2.10 on 2022-02-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_remove_collectionaction_scheduler_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionaction',
            name='attachment',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
