# Generated by Django 3.2.10 on 2022-02-04 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_collectionaction_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionaction',
            name='invoice',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, related_name='collectionaction_invoice', to='sales.invoice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduleritem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('call_due', 'Call due'), ('call_done', 'Call done'), ('finished', 'Finished'), ('legal_action', 'Legal Action')], default='pending', max_length=100),
        ),
    ]
