# Generated by Django 3.2.10 on 2022-02-04 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20220204_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collectionaction_invoice', to='sales.invoice'),
        ),
    ]
