# Generated by Django 3.2.10 on 2022-02-04 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_collectionaction_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionaction',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='collectionaction',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='scheduleritem',
            name='is_legal',
        ),
        migrations.CreateModel(
            name='CollectionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectioninvoice_invoice', to='sales.collectionaction')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectioninvoice_invoice', to='sales.invoice')),
            ],
        ),
    ]
