# Generated by Django 3.2.10 on 2022-02-04 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_address_customer'),
        ('sales', '0014_auto_20220204_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionaction',
            name='customer',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, related_name='collectionaction_customer', to='customer.customer'),
            preserve_default=False,
        ),
    ]
