# Generated by Django 3.2.10 on 2022-02-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_collectionaction_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionaction',
            name='action_status',
            field=models.CharField(choices=[('due', 'Due'), ('done', 'Done'), ('pending', 'Pending')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduleritem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('call_due', 'Call due'), ('call_done', 'Call done'), ('in_progress', 'In progress'), ('finished', 'Finished'), ('legal_action', 'Legal Action')], default='pending', max_length=100),
        ),
    ]
