# Generated by Django 3.2.10 on 2022-02-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_alter_invoice_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='meta_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
