# Generated by Django 3.2.10 on 2022-02-09 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_address_customer'),
        ('sales', '0020_alter_invoice_meta_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_iddress_id',
            new_name='ec_invoice_type_id',
        ),
        migrations.RenameField(
            model_name='invoiceorder',
            old_name='order_numbre',
            new_name='ec_order_id',
        ),
        migrations.RenameField(
            model_name='invoiceorder',
            old_name='order_vnit_value_Curr',
            new_name='order_vnit_value_curr',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_type_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='service_type',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_address',
            field=models.ForeignKey(default=1316, on_delete=django.db.models.deletion.PROTECT, to='customer.address'),
            preserve_default=False,
        ),
    ]
