# Generated by Django 3.2.10 on 2022-02-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_auto_20220209_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ec_delivery_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
