# Generated by Django 3.2.10 on 2022-02-09 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_auto_20220209_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_iddress_id',
            new_name='ec_invoice_iddress_id',
        ),
    ]
