# Generated by Django 3.2.10 on 2022-02-09 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_rename_invoice_iddress_id_invoice_ec_invoice_iddress_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='ec_invoice_iddress_id',
            new_name='ec_invoice_address_id',
        ),
    ]
