# Generated by Django 3.2.10 on 2022-02-10 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_rename_ec_invoice_iddress_id_invoice_ec_invoice_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioninvoice',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collectioninvoice_invoice', to='sales.invoice'),
        ),
    ]
