# Generated by Django 3.2.10 on 2022-02-15 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_collectionactionattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionaction',
            name='attachment',
        ),
    ]
