# Generated by Django 3.2.10 on 2022-02-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_remove_collectionaction_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collectionaction',
            name='action_status',
            field=models.CharField(choices=[('due', 'Processed'), ('done', 'Follow ups'), ('finished', 'Finished')], default='pending', max_length=100),
        ),
    ]
