# Generated by Django 3.2.10 on 2022-02-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_auto_20220222_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionaction',
            name='action_status',
            field=models.CharField(choices=[('done', 'Processed'), ('due', 'Follow ups'), ('finished', 'Finished')], default='pending', max_length=100),
        ),
    ]
