# Generated by Django 3.2.10 on 2022-03-25 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_auto_20220317_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_iddress',
            new_name='invoice_address',
        ),
    ]
