# Generated by Django 3.2.10 on 2022-04-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0034_rename_invoice_iddress_invoice_invoice_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='credit_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_credit_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
