# Generated by Django 3.2.10 on 2022-04-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0035_auto_20220420_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer_credit_limit',
        ),
    ]
