# Generated by Django 3.2.10 on 2022-04-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_auto_20220420_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_credit_limit',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
