# Generated by Django 3.2.10 on 2022-04-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0037_auto_20220420_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduleritem',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduleritem',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
