# Generated by Django 3.2.10 on 2022-04-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0038_auto_20220422_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
