# Generated by Django 3.2.10 on 2022-04-26 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0039_invoice_delivery_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleritem',
            name='total_invoice',
        ),
        migrations.AddField(
            model_name='scheduleritem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduleritem_invoice', to='sales.invoice'),
        ),
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, null=True)),
                ('harm_code', models.CharField(max_length=100, null=True)),
                ('intrastat', models.CharField(max_length=100, null=True)),
                ('country_of_origin', models.CharField(max_length=100, null=True)),
                ('weight', models.DecimalField(decimal_places=5, max_digits=12, null=True)),
                ('value', models.DecimalField(decimal_places=5, max_digits=12, null=True)),
                ('value_curr', models.DecimalField(decimal_places=5, max_digits=12, null=True)),
                ('vat_percentage', models.DecimalField(decimal_places=5, max_digits=12, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customerinvoice_invoice', to='sales.invoice')),
            ],
        ),
    ]
