# Generated by Django 3.2.10 on 2022-04-28 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0040_auto_20220426_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleritem',
            name='sent_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
