# Generated by Django 3.2.10 on 2022-04-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0042_invoice_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='street_address1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='street_address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
