# Generated by Django 3.2.10 on 2022-04-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0043_auto_20220428_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='city',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='email',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='financial_block',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='street_address1',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='street_address2',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
