# Generated by Django 3.2.10 on 2022-04-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0044_auto_20220428_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='financial_block',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_fax',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='street_address1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='street_address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
