# Generated by Django 3.2.10 on 2022-04-28 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0045_auto_20220428_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='financial_block',
        ),
    ]
