# Generated by Django 3.2.10 on 2022-04-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0046_remove_invoice_financial_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='financial_block',
            field=models.BooleanField(default=False),
        ),
    ]
