# Generated by Django 3.2.10 on 2022-05-04 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0041_auto_20220428_1652'),
        ('sales', '0047_invoice_financial_block'),
    ]

    operations = [
    ]
