# Generated by Django 3.2.10 on 2022-05-06 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0048_merge_20220504_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='currency_custome_value',
            new_name='currency_customer_value',
        ),
    ]
