# Generated by Django 3.2.10 on 2022-05-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0049_rename_currency_custome_value_invoice_currency_customer_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ec_invoice_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='is_re_processed',
            field=models.BooleanField(default=False),
        ),
    ]
