# Generated by Django 3.2.10 on 2022-05-12 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_auto_20220510_1109'),
        ('sales', '0052_auto_20220512_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleritem',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduleritem_customer', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='scheduleritem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduleritem_invoice', to='sales.invoice'),
        ),
    ]
