# Generated by Django 3.2.10 on 2022-05-16 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0053_auto_20220512_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='currency_customer_value',
        ),
    ]
