# Generated by Django 3.2.10 on 2022-05-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0054_remove_invoice_currency_customer_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
