# Generated by Django 3.2.10 on 2022-06-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0059_alter_collectionaction_action_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionaction',
            name='action_status',
            field=models.CharField(choices=[('done', 'Processed'), ('due', 'Follow up'), ('completed', 'Completed'), ('finished', 'Finished'), ('pending', 'Pending')], max_length=100, null=True),
        ),
    ]
