# Generated by Django 3.2.10 on 2022-06-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0060_alter_collectionaction_action_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceorder',
            name='article_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoiceorder',
            name='project_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoiceorder',
            name='purchase_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
