# Generated by Django 3.2.10 on 2022-06-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0061_auto_20220621_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionaction',
            name='action_status',
            field=models.CharField(choices=[('done', 'Processed'), ('due', 'Follow up'), ('completed', 'Completed'), ('finished', 'Finished'), ('pending', 'Pending')], default='pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collectionaction',
            name='action_type',
            field=models.CharField(blank=True, choices=[('call', 'Call'), ('email', 'Email'), ('chat', 'Chat'), ('offline_message', 'Offline message'), ('remarks', 'Remarks'), ('follow_up', 'Follow up'), ('call_and_email', 'Call and email'), ('call_and_message', 'Call and message')], max_length=100, null=True),
        ),
    ]
