# Generated by Django 3.2.10 on 2022-06-24 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0063_alter_collectionaction_action_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=12, null=True)),
                ('currency_amount', models.DecimalField(decimal_places=5, max_digits=12, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoicediscount_invoice', to='sales.invoice')),
            ],
        ),
    ]
