# Generated by Django 3.2.10 on 2022-06-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0064_invoicediscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
