# Generated by Django 3.2.10 on 2022-07-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0066_invoice_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order_nrs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
