# Generated by Django 3.2.10 on 2022-12-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0067_alter_invoice_order_nrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionaction',
            name='is_cust_base',
            field=models.BooleanField(default=False),
        ),
    ]
