# Generated by Django 3.2.10 on 2023-01-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0069_alter_invoice_order_nrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
