# Generated by Django 2.2.6 on 2022-09-21 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('initials', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProcessMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderScreenParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pws.OrderScreenParameter')),
            ],
        ),
        migrations.CreateModel(
            name='OrderScreenMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_value', models.CharField(max_length=400, null=True)),
                ('display_ids', models.CharField(blank=True, max_length=400, null=True)),
                ('is_compulsory', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderscreenmaster_company', to='pws.Company')),
                ('order_screen_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderscreenmaster_screen_master', to='pws.OrderScreenParameter')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFlowMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderflowmapping_company', to='pws.Company')),
                ('process', models.ManyToManyField(to='pws.OrderProcessMaster')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderflowmapping_service', to='pws.ServiceMaster')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAllocationFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_date', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderallocationflow_company', to='pws.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec_user', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('shift', models.CharField(blank=True, choices=[(1, 'First shift'), (2, 'Second shift'), (3, 'Third shift'), (4, 'General shift')], max_length=50, null=True)),
                ('permanent_shift', models.CharField(blank=True, choices=[(1, 'First shift'), (2, 'Second shift'), (3, 'Third shift'), (4, 'General shift')], max_length=50, null=True)),
                ('operator_group', models.CharField(blank=True, choices=[(1, 'Group B'), (2, 'Group FEE'), (3, 'Customer'), (4, 'Backoffice and others')], max_length=50, null=True)),
                ('operator_type', models.CharField(blank=True, choices=[(1, 'Planet engineer'), (2, 'Knowledge leaders'), (3, 'Group leaders'), (4, 'Customer'), (5, 'PWS incharge'), (6, 'Network administrator'), (7, 'Group B')], max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company', models.ManyToManyField(blank=True, null=True, to='pws.Company')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pws.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_mail', models.CharField(max_length=200, null=True)),
                ('ord_rec_mail', models.CharField(max_length=200, null=True)),
                ('ord_exc_gen_mail', models.CharField(max_length=200, null=True)),
                ('ord_exc_rem_mail', models.CharField(max_length=200, null=True)),
                ('ord_comp_mail', models.CharField(max_length=200, null=True)),
                ('mail_from', models.CharField(max_length=100, null=True)),
                ('is_req_multi_operator', models.BooleanField(default=True)),
                ('is_req_files', models.BooleanField(default=True)),
                ('is_send_attachment', models.BooleanField(default=True)),
                ('no_of_jobs', models.IntegerField(null=True)),
                ('is_smart_plate', models.BooleanField(default=True)),
                ('is_checklist_req', models.BooleanField(default=True)),
                ('is_exp_file_attachment', models.BooleanField(default=True)),
                ('is_checklist_pdf', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companyparameter_company', to='pws.Company')),
            ],
        ),
    ]
