# Generated by Django 2.2.6 on 2022-09-29 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pws', '0006_auto_20220927_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertechparameter',
            name='inner_layer_copper_foil',
            field=models.CharField(blank=True, choices=[('ILCF_12', '12 µm'), ('ILCF_18', '18 µm'), ('ILCF_35', '35 µm'), ('ILCF_70', '70 µm'), ('ILCF_105', '105 µm')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='inner_layer_core_thickness',
            field=models.CharField(blank=True, choices=[('ILCT_710', '710 µm'), ('ILCT_508', '508 µm'), ('ILCT_360', '360 µm'), ('ILCT_254', '254 µm'), ('ILCT_200', '200 µm'), ('ILCT_100', '100 µm'), ('ILCT_75', '75 µm'), ('ILCT_50', '50 µm')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordertechparameter',
            name='outer_layer_copper_foil',
            field=models.CharField(blank=True, choices=[('OLCF_12', '12 µm (end +/-30 µm)'), ('OLCF_18', '18 µm (end +/-35 µm)'), ('OLCF_35', '35 µm (end +/-60 µm)'), ('OLCF_70', '70 µm (end +/-95 µm)'), ('OLCF_105', '105 µm (end +/-130 µm)')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='NcCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pws.NcCategory')),
            ],
        ),
    ]
