# Generated by Django 2.2.6 on 2022-10-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pws', '0012_auto_20221003_1105'),
        ('pws', '0010_auto_20220930_1211'),
    ]

    operations = [
    ]
