# Generated by Django 2.2.6 on 2022-10-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pws', '0014_auto_20221004_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_order_nr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
