# Generated by Django 2.2.6 on 2022-10-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pws", "0020_auto_20221010_1903"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderexception",
            name="problem_description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="predefineexceptionproblem",
            name="is_problem",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("schematic", "Schematic"),
                    ("footprint", "Footprint"),
                    ("placement", "Placement"),
                    ("routing", "Routing"),
                    ("gerber_release", "Gerber Release"),
                    ("analysis", "Analysis"),
                    ("incoming", "Incoming"),
                    ("bom_incoming", "BOM incoming"),
                    ("SI", "SI"),
                    ("SICC", "SICC"),
                    ("BOM_CC", "BOM CC"),
                    ("FQC", "FQC"),
                    ("panel", "Panel"),
                    ("upload_panel", "Upload Panel"),
                    ("cancel", "Cancel"),
                    ("exception", "Exception"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderallocationflow",
            name="allocation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pre_due_date", "PreDueDate"),
                    ("delivery_date", "Delivery date"),
                    ("systemin_time", "Systemin time"),
                    ("total_minutes", "Total minutes"),
                    ("order_date", "Order date"),
                    ("delivery_and_order_date", "Delivery and Order date"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
