# Generated by Django 2.2.6 on 2022-11-02 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pws', '0027_auto_20221021_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEfficiencyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_code', models.CharField(max_length=100)),
                ('layer', models.CharField(max_length=100)),
                ('layer_point', models.IntegerField()),
                ('order_status', models.CharField(max_length=100)),
                ('prep_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order_layer', models.CharField(max_length=100)),
                ('total_work_efficiency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pws.Company')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pws.Operator')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pws.Order')),
            ],
        ),
    ]
