# Generated by Django 2.2.6 on 2022-11-02 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pws', '0028_userefficiencylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderflowmapping',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orderflowmapping_service', to='pws.Service'),
        ),
    ]
