# Generated by Django 2.2.6 on 2022-11-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pws', '0038_auto_20221125_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonconformity',
            name='nc_from',
            field=models.CharField(blank=True, choices=[('schematic', 'Schematic'), ('footprint', 'Footprint'), ('placement', 'Placement'), ('routing', 'Routing'), ('gerber_release', 'Gerber Release'), ('analysis', 'Analysis'), ('incoming', 'Incoming'), ('BOM_incoming', 'BOM incoming'), ('SI', 'SI'), ('SICC', 'SICC'), ('BOM_CC', 'BOM CC'), ('FQC', 'FQC'), ('panel', 'Panel'), ('upload_panel', 'Upload Panel'), ('cancel', 'Cancel'), ('exception', 'Exception'), ('finished', 'Order Finish')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('schematic', 'Schematic'), ('footprint', 'Footprint'), ('placement', 'Placement'), ('routing', 'Routing'), ('gerber_release', 'Gerber Release'), ('analysis', 'Analysis'), ('incoming', 'Incoming'), ('BOM_incoming', 'BOM incoming'), ('SI', 'SI'), ('SICC', 'SICC'), ('BOM_CC', 'BOM CC'), ('FQC', 'FQC'), ('panel', 'Panel'), ('upload_panel', 'Upload Panel'), ('cancel', 'Cancel'), ('exception', 'Exception'), ('finished', 'Order Finish')], max_length=50, null=True),
        ),
    ]
