# Generated by Django 2.2.6 on 2022-12-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pws', '0044_auto_20221206_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
