# Generated by Django 2.2.6 on 2022-12-29 10:28

import attachment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pws', '0047_auto_20221223_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_attachment',
            name='name',
            field=models.CharField(default='', max_length=270),
        ),
        migrations.AlterField(
            model_name='order_attachment',
            name='url',
            field=models.FileField(max_length=270, upload_to=attachment.models.update_filename),
        ),
    ]
