# Generated by Django 2.2.6 on 2023-01-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pws', '0049_auto_20230105_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_term',
            field=models.CharField(blank=True, choices=[('DEL_0', '0 Working day'), ('DEL_1', '1 Working day'), ('DEL_2', '2 Working days'), ('DEL_3', '3 Working days'), ('DEL_4', '4 Working days'), ('DEL_5', '5 Working days'), ('DEL_6', '6 Working days'), ('DEL_7', '7 Working days'), ('DEL_8', '8 Working days'), ('DEL_9', '9 Working days'), ('DEL_10', '10 Working days'), ('DEL_12', '12 Working days'), ('DEL_15', '15 Working days'), ('DEL_20', '20 Working days'), ('DEL_25', '25 Working days'), ('DEL_30', '30 Working days'), ('No', 'Not Available')], max_length=50, null=True),
        ),
    ]
