# Generated by Django 2.2.6 on 2023-01-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pws', '0050_auto_20230106_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertechparameter',
            name='top_solder_mask',
            field=models.CharField(blank=True, choices=[('Top_SM_Green', 'Green'), ('Top_SM_Black', 'Black'), ('Top_SM_White', 'White'), ('Top_SM_None', 'None'), ('Top_SM_Red', 'Red'), ('Top_SM_Blue', 'Blue'), ('Top_SM_Transparent', 'Transparent'), ('Top_SM_PCBPixture', 'PCB PIXture')], max_length=100, null=True),
        ),
    ]
