# Generated by Django 2.2.6 on 2023-01-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pws', '0052_operator_show_own_records_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pcb_name',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
