# Generated by Django 2.2.6 on 2023-01-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pws', '0054_auto_20230119_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='panel_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='panel_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
