# Generated by Django 2.2.6 on 2023-02-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pws', '0062_auto_20230213_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='userefficiencylog',
            name='knowledge_leaders',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
