# Generated by Django 2.2.6 on 2023-02-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pws', '0065_auto_20230217_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('order_status', models.CharField(blank=True, max_length=50, null=True)),
                ('import_from', models.CharField(blank=True, max_length=50, null=True)),
                ('compared_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
