# Generated by Django 2.2.6 on 2023-03-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pws', '0071_performanceindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceindex',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
