# Generated by Django 2.2.6 on 2023-03-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pws', '0073_orderexception_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderexception',
            old_name='remarks',
            new_name='internal_remark',
        ),
    ]
