# Generated by Django 2.2.6 on 2022-09-08 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AuditReportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('action_on', models.DateTimeField(blank=True, null=True)),
                ('ip_addr', models.CharField(default='', max_length=45)),
                ('descr', models.TextField(default='')),
                ('group', models.CharField(default='', max_length=45)),
                ('status_code', models.CharField(default='', max_length=45)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auditlog.AuditAction')),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Auditlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('action_on', models.DateTimeField(auto_now=True)),
                ('ip_addr', models.CharField(default='', max_length=45)),
                ('descr', models.TextField(default='')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auditlog.AuditAction')),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
        ),
    ]
