# Generated by Django 2.2.6 on 2022-11-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0002_auto_20221118_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='prep_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
