# Generated by Django 3.2.10 on 2022-04-27 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0040_auto_20220426_1207'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=100)),
                ('status_code', models.CharField(default='', max_length=45)),
                ('action', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.CharField(default='', max_length=45, null=True)),
                ('document_no', models.CharField(default='', max_length=45, null=True)),
                ('old_value', models.DecimalField(decimal_places=5, max_digits=12, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.invoice')),
            ],
        ),
    ]
