# Generated by Django 3.2.10 on 2022-05-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0003_auto_20220516_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='group',
            field=models.CharField(default='', max_length=45),
        ),
    ]
